Repository 23technologies/testbed-gardener, pull requests merged in 2021-02, with the labels that each got.

#71 Disables backup for standard env
  terraform/environments/standard.tfvars
Labels: Type: Bugfix

#72 github: disable daily betacloud workflow
  .github/disabled/daily-betacloud.yml
Labels: Type: CI

#73 Fixes keycloak secret retrieval
  terraform/files/install_keycloak.sh
Labels: Type: Bugfix

#74 Prints URL, username and password on successful run
  terraform/outputs.tf
Labels: Type: Feature

#75 Fixes static backup-config for seeds
  terraform/files/acre.yaml.tmpl
Labels: Type: Bugfix

#76 Removes k3s token, no longer needed
  terraform/random.tf
Labels: Type: Bugfix

#77 Updates README.md
  README.md
Labels: Type: Documentation

#78 Adds bc3 environment
  terraform/environments/gx-bc3.tfvars
Labels: Type: Feature

#79 Fixes mgmt-address state file
  terraform/outputs.tf
Labels: Type: Bugfix

#80 Adds auto-create of demo-shoot
  terraform/files/bootstrap.sh
  terraform/files/create_shoot.sh
  terraform/files/demo-shoot.yaml.tmpl
  terraform/mgmt.tf
Labels: Type: Feature

#84 fix/gardenctl url
  terraform/Makefile
  terraform/files/bootstrap.sh
Labels: Type: Bugfix

#85 Deploys a demo app in the demo-shoot
  terraform/files/bootstrap.sh
  terraform/files/install_demo_app.sh
  terraform/mgmt.tf
Labels: Type: Feature

#86 Adds asciinema demo
  README.md
Labels: Type: Documentation
