Repository 23technologies/testbed-gardener, pull requests merged in 2021-01, with the labels that each got.

#23 Integrate Keycloak
  terraform/environment-gx-scs-staging.tfvars
  terraform/files/bootstrap.sh
  terraform/files/deploy.sh
  terraform/files/gx-scs-staging/acre.yaml.tmpl
  terraform/files/install_keycloak.sh
  terraform/mgmt.tf
Labels: enhancement

#25 Wait for cloud init.
  terraform/files/bootstrap.sh
  terraform/files/wait.sh
  terraform/mgmt.tf
Labels: Type: Bugfix

#27 feat/os purge
  README.md
  terraform/Makefile
  terraform/environment-gx-bc.tfvars
  terraform/files/bootstrap.sh
  terraform/files/gx-bc/acre.yaml.tmpl
Labels: Type: Feature

#37 Add Loop for Keypair purge
  terraform/Makefile
Labels: Type: Bugfix

#38 fix/node readyness
  terraform/Makefile
  terraform/files/bootstrap.sh
  terraform/files/node_readyness.sh.tmpl
  terraform/mgmt.tf
Labels: Type: Bugfix

#39 Fix Keypair removal
  terraform/Makefile
Labels: Type: Bugfix

#40 fix/ssh key removal
  terraform/Makefile
  terraform/nova.tf
Labels: Type: Bugfix

#41 refactor/acre templating
  terraform/Makefile
  terraform/environment-
  terraform/environment-default.tfvars
  terraform/environment-gx-bc.tfvars
  terraform/environment-gx-bc2.tfvars
  terraform/environment-gx-cc.tfvars
  terraform/environment-gx-scs-staging.tfvars
  terraform/environment-gx-scs.tfvars
  terraform/files/acre.yaml.tmpl
  terraform/files/gx-bc/acre.yaml.tmpl
  terraform/files/gx-bc2/acre.yaml.tmpl
  terraform/files/gx-cc/acre.yaml.tmpl
  terraform/files/gx-scs/acre.yaml.tmpl
  terraform/mgmt.tf
  terraform/variables.tf
Labels: Type: Refactoring

#43 Use betacloud as default environment and name it default
  README.md
  terraform/Makefile
  terraform/clouds.yaml.sample
  terraform/environment-default.tfvars
  terraform/secure.yaml.sample
  terraform/variables.tf
Labels: Type: Feature

#44 github: add 'Daily betacloud' workflow
  .github/workflows/daily-betacloud.yml
Labels: Type: CI

#51 Fix if statement
  terraform/Makefile
Labels: Type: Bugfix

#52 Installs openstackclient via pip
  .github/workflows/daily-betacloud.yml
Labels: Type: Bugfix

#53 Installs openstackclient
  .github/workflows/daily-betacloud.yml
Labels: Type: Bugfix

#54 Displays github action-vm ip
  .github/workflows/daily-betacloud.yml
Labels: Type: Feature

#57 Renamed default env to standard
  .github/workflows/daily-betacloud.yml
  terraform/Makefile
  terraform/clouds.yaml.sample
  terraform/environment-standard.tfvars
  terraform/secure.yaml.sample
Labels: Type: Bugfix

#59 terraform: move environment files
  terraform/Makefile
  terraform/environments/gx-bc.tfvars
  terraform/environments/gx-bc2.tfvars
  terraform/environments/gx-scs-staging.tfvars
  terraform/environments/gx-scs.tfvars
  terraform/environments/standard.tfvars
Labels: Type: Feature

#60 terraform: make terraform binary configurable
  terraform/Makefile
Labels: Type: Feature

#61 terraform: use cloud-init to copy ssh keypair
  terraform/k8s-main.tf
  terraform/mgmt.tf
  terraform/workers.tf
Labels: Type: Feature

#62 terraform: use a local keypair
  terraform/Makefile
  terraform/mgmt.tf
  terraform/nova.tf
  terraform/outputs.tf
Labels: Type: Feature

#65 Use terraform 0.14
  .github/workflows/check-terraform-syntax.yml
  terraform/main.tf
Labels: Type: Bugfix

#66 github: use terragrunt
  .github/workflows/daily-betacloud.yml
  terraform/terragrunt.hcl
Labels: Type: Feature

#67 Add a requirements.txt file
  .github/workflows/daily-betacloud.yml
  requirements.txt
Labels: Type: Feature

#69 github: use terraform 0.14.5
  .github/workflows/daily-betacloud.yml
Labels: Type: CI

#70 terraform: use terraform-provider-openstack 1.35.0
  terraform/main.tf
Labels: Type: Feature
